spring:
  datasource:
    url: jdbc:postgresql://db:5432/afdesign
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    banner-mode: "off"

security:
    jwt:
      secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32CHARS_MIN"
      expiration-seconds: 3600

server:
  port: 8080

